#!/usr/bin/env bash

file="$1"

# Must have exactly one argument
if test "$#" -ne 1
then
    echo "ERROR: No input CSV file provided"
    exit 1
fi

# Check file exists
if test ! -f "$file"
then
    echo "ERROR: Input file not found in the current directory"
    exit 1
fi

# Check file is not empty
if test ! -s "$file"
then
    echo "ERROR: Empty file provided"
    exit 1
fi

# Check that the input file has a .csv extension
if ! echo "$file" | grep '\.csv$' > /dev/null
then
    echo "ERROR: Input file expected in a CSV format"
    exit 1
fi