#!/usr/bin/env bash

file="$1"

# Stop early if the user did not give an input file.
if test -z "$file"
then
    echo "ERROR: No input CSV file provided"
    exit 1
fi
# Check number of arguments
if test "$#" -ne 2
then
    echo "Usage: ./clean <input_file> <output_file>" >&2
    exit 1
fi
